sudo: false
dist: trusty

language: cpp

compiler:
  - gcc
  - clang

os:
  - linux

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

install:
  - cmake -HProjects/CMake -BBuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cd Build
  - make
  - cd ..

script:
  - cd Build
  - ctest -V
  - cd ..

after_success:
  - coveralls --exclude 'Tests' --exclude ${OPENCL_ROOT} --exclude-pattern '.*CompilerId.*' --gcov-options '\-lp'
