sudo: required
dist: trusty

language: cpp

compiler:
  - gcc
  - clang

os:
  - linux

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

before_install:
  - sudo apt-get update -qq -y;
  - sudo apt-get install -qq git cmake opencl-headers build-essential unzip
    # Install Catalyst dependencies
  - sudo apt-get install -qq -y cdbs dh-make dkms execstack dh-modaliases linux-headers-generic libqtgui4 xserver-xorg-dev-lts-trusty lib32gcc1 libxrandr2 libxcursor1 libgl1-mesa-glx libxinerama1
    # From the http://wiki.cchtml.com/index.php/Ubuntu_Trusty_Installation_Guide#Installing_Proprietary_Drivers_a.k.a._Catalyst.2Ffglrx
    # Download the latest Catalyst package
  - mkdir catalyst-14.6beta1.0jul11
  - pushd catalyst-14.6beta1.0jul11
  - wget --referer='http://support.amd.com/en-us/download/desktop?os=Linux+x86' http://www2.ati.com/drivers/beta/linux-amd-catalyst-14.6-beta-v1.0-jul11.zip
  - unzip linux-amd-catalyst-14.6-beta-v1.0-jul11.zip
    # Create and install .deb packages
  - pushd fglrx-14.20
  - sudo ./amd-driver-installer-14.20-x86.x86_64.run --buildpkg Ubuntu/trusty
  - sudo apt-get -f install
  - sudo dpkg -i fglrx*.deb
  - export OPENCL_ROOT="${TRAVIS_BUILD_DIR}/Source/OpenCL"
  - pip install --user cpp-coveralls
  - popd
  - popd

install:
  - mkdir -p ${OPENCL_ROOT}
  - pushd ${OPENCL_ROOT}
  - wget -w 1 -r -np -nd -nv -A h,hpp https://www.khronos.org/registry/cl/api/2.1/cl.hpp
  - popd
  - cmake -HProjects/CMake -BBuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cd Build
  - make
  - cd ..

script:
  - cd Build
  - ctest -V
  - cd ..

after_success:
  - coveralls --exclude 'Tests' --exclude ${OPENCL_ROOT} --exclude-pattern '.*CompilerId.*' --gcov-options '\-lp'
